# Angel One Credentials
ANGEL_API_KEY = "WM6i3ikL"
ANGEL_CLIENT_ID = "AABY364105"
ANGEL_PIN = "6954"
ANGEL_TOTP_TOKEN = "D5PMGU3B674K4YFIQNE7CKDUSU"

# Dhan Credentials
DHAN_CLIENT_ID = "2512259667" 
DHAN_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzY3MDEwOTg3LCJpYXQiOjE3NjY5MjQ1ODcsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTAwMDg3ODI5In0.XzHF-j-zwG2rLjjzIafmudOPKZ6BayqrOptu_0RlO1s0Af4XyWsCLycePnfyRaPuYq5k5I5lSnw_3WKCDFLyzg"

# Email Credentials
GMAIL_USER = "akhils8493@gmail.com"
GMAIL_PASSWORD = "tptr wtof dhkb jtht" 


